version: "3.5"
services:
  mariadb:
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
  wordpress:
    user: "${UID}:${GID}"
    build: .
    depends_on:
      - mariadb
    ports:
      - 80:80
    volumes:      
      - type: bind
        source: ./wp/utils
        target: /var/www/html/utils
      - type: bind
        source: ./casamento
        target: /var/www/html/wp-content/themes/casamento
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example      
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost' );
        define('WP_SITEURL', 'http://localhost' );
        define('debug', true);
